name: Monitor ABC Rewards Website
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
jobs:
  crawl_for_broken_links:
    runs-on: self-hosted
    name: Broken-Links-Crawler
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - name: Checking links
      id: checking
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://abc-rewards.abcdigital.io'
        exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://twitter.com'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
